config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories do
    resources :expenses, only: %i[index]
  end

  resources :expenses, only: %i[create update destroy new]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "splash#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, optional: true
  has_many :expenses, foreign_key: 'category_id', dependent: :destroy
  validates :icon, format: URI::DEFAULT_PARSER.make_regexp(%w[http https])
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  def total_expenses
    expenses.sum(:amount)
  end
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id', optional: true
  belongs_to :category, foreign_key: 'category_id', optional: true
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :expenses, dependent: :destroy, foreign_key: 'user_id'
  has_many :categories, dependent: :destroy, foreign_key: 'author_id'
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :email, presence: true, length: { minimum: 3, maximum: 25 }
  validates :password, presence: true, length: { minimum: 3, maximum: 25 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :email_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /categories or /categories.json
  def index
    @categories = Category.all
    @user = current_user
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(icon: params[:icon], name: params[:name], author_id: current_user.id)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.fetch(:category, {})
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[show edit update destroy]
  before_action :authenticate_user!
  # GET /expenses or /expenses.json
  def index
    @category = Category.find(params[:category_id])
    @expenses = @category.expenses.order('created_at DESC')
    @total_expense = @category.total_expenses
  end

  # GET /expenses/1 or /expenses/1.json
  def show; end

  # GET /expenses/new
  def new
    @expense = Expense.new
    @categories = current_user.categories
  end

  # GET /expenses/1/edit
  def edit; end

  # POST /expenses or /expenses.json
  def create
    @categories = current_user.categories
    @expense = Expense.new(name: params[:name], amount: params[:number], category_id: params[:category],
                           author_id: current_user.id)
    if @expense.save
      redirect_to category_expenses_path(params[:category])
    else
      render :new
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.fetch(:expense, {})
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index
    return unless user_signed_in?

    redirect_to categories_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authenticate_user!
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.fetch(:user, {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_bar_content(controller)
    case controller
    when 'categories'
      'Categories'
    when 'splash'
      'Welcome'
    when 'devise/sessions'
      'LOGIN'
    when 'devise/registrations'
      'REGISTER'
    when 'expenses'
      'Expenses'
    else
      'Not implemented'
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field-wrapper">

    <%= text_field_tag "icon", '', class: 'cat-field', placeholder: 'Icon Url' %>
    <%= text_field_tag "name", '', class: 'cat-field', placeholder: 'Name' %>
  </div>
  <div class="cat-submit">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>
<% if @user.categories.length == 0 %>
  <p>There are no categories yet.</p>
<% else %>
<% @user.categories.each do |category| %>
  <div class="category-wrapper" onclick="location.href='<%= category_expenses_path(category) %>'">
    <div class="icon-wrapper">
      <%= image_tag (category.icon), class:"cat-icon" %>
    </div>
    <div class="cat-info">
      <div class="cat-name">
        <%= category.name %>
      </div>
      <div class="cat-date">
        <%= category.created_at.strftime('%Y %b %d') %>
      </div>
    </div>
    <div class="cat-total">
      <%= category.total_expenses %>
    </div>
  </div>
  <% end %>
<% end %>
<div class="cat-button">
  <%= link_to "Add a new category", new_category_path, :class => "add-new-category" %>
</div>

app/views/categories/new.html.erb
<%= render "form", category: @category %>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>">
</div>

app/views/expenses/_form.html.erb
<%= form_with url: categories_path, method: :post, local: true do %>
   <div>
    <%= label_tag "title"%>
    <%= text_field_tag "title" %>
   <%= label_tag "text" %>
    <%= text_area_tag "text" %>
    <%= submit_tag "Send" %>
 </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Show this expense", @expense %> |
  <%= link_to "Back to expenses", expenses_path %>
</div>

app/views/expenses/index.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to categories_path, :class => "expenses-back" do %>
    <%= image_tag("left-arrow.png", :alt => "back") %>
  <% end %>
<% if @expenses.length == 0 %>
  <p>There are no expenses yet.</p>
<% else %>
<div class="total-expense">
  <p>Total: <%= @total_expense %></p>
</div>
<div class="expenses">
  <% @expenses.each do |expense| %>
  <div class="expense-item">
    <div class="expense-name">
      <p><%= expense.name %></p>
    </div>
    <div class="expense-amount">
      <p><%= expense.amount %></p>
    </div>
  </div>
  <% end %>
</div>
<% end %>

<div class="cat-button">
  <%= link_to "Add a new expense", new_expense_path, :class => "add-new-category" %>
</div>

app/views/expenses/new.html.erb
<%= form_with url: expenses_path, method: :post, local: true do %>
   <div class="field-wrapper">
   
    <%= text_field_tag "name", '', class: 'cat-field', placeholder: 'Name' %>
    <%= number_field_tag "number", '', class: 'cat-field', placeholder: 'Amount', step: :any %>
    <%= label_tag "Select the category"%>
    <%= select_tag "category", options_from_collection_for_select(@categories, 'id', 'name') %>
    <div class="cat-submit">
    <%= submit_tag "Send" %>
    </div>
 </div>
<% end %>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expense %>

<div>
  <%= link_to "Edit this expense", edit_expense_path(@expense) %> |
  <%= link_to "Back to expenses", expenses_path %>

  <%= button_to "Destroy this expense", @expense, method: :delete %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <%= link_to :back, :class => "navbar-back" do %>
    <%= image_tag("left-arrow.png", :alt => "back") %>
  <% end %>
  <h1><%= nav_bar_content(params[:controller]) %></h1>
  <div class="user-info">
     <ul class="navbar-user" >
        <% if user_signed_in? %>
          <li>
            Hi, <%= current_user.name%>
          </li>
          <li>
            <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: "logout-button" %>
          </li>
          
        <% else %>
          <li>
            <%= link_to 'Log in', new_user_session_path, class: "login-button" %>
          </li>  
        <% end %>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budgetsnapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% unless controller_name == "splash" %>
      <%= render "layouts/navbar" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/splash/index.html.erb
<div class="splash-wrapper">
  <div class="splash-title">BudgetSnapp</div>
  <div class="splash-buttons">
    <%= link_to 'Sign up', new_user_registration_path, class: "splash-button" %>
    <%= link_to 'Log in', new_user_session_path, class: "splash-button" %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>